### ISSUE TITLE
[Suggestion] Block leaderboard unless answer submitted

### ISSUE THREAD

**Issue by borrachiva** [hryanjones/guess-my-word#32]
It is possible, by changing the Difficulty dropdown while on the Completion Board to view the correct answers for a word challenge you have not already completed.  

Steps to Repro:
1) Access the https://hryanjones.com/guess-my-word/
2) With the difficulty dropdown on Normal, submit guesses for the word until puzzle is solved.  The "give up" option can be used to speed through this step.
3) Click on the Completion Board link that appears.
4) While on the Completion Board link, change the Difficulty dropdown to "Hard"
5) Observe that the Hard word answer is visible in the Completion board guess list.

Results:  Users can see the answers to Daily Word Challenges before they have attempted to solve them.

Expected Results: Difficulty dropdown to be unavailable from Completion Board screen, or to take user back to the Guess screen if selected while on the Completion Board.

**Comment by hryanjones** [comment]
That definitely sounds like a bug, but I wasn't able to reproduce this.

I also can't think of a way that this is possible because the way that I get board data from the backend is this:
- when you've played that difficulty (as stored in the browser) it includes the `name` you submitted and part of your `guesses`
- the board server then checks this name against it's list of people that have played that day and verifies that the guesses match then returns guesses for people if it matches an existing entry

So, it shouldn't be possible for this to happen unless you'd already played the hard word (and successfully submitted), but maybe there's a piece I'm missing.

Also, just to verify these are the steps I took:
1. play the normal word (successfully)
2. submit my name to the board
3. navigate to the board
  - observe that guesses are included
4. use the difficulty dropdown to change to "hard"
  - **expected & actual**: can't see guesses on the hard version of the board

**Comment by borrachiva** [comment]
Hey, thanks for the thorough response!  I went through it again this morning while taking video, and realized that while I see the guess data, I don't actually see the guessed words or the answer.  

I like to think I'm still in possession of enough faculties during quarantine that I did actually see it when I first noticed this, but it's also possible I conflated the normal board and the hard.  Weirder things have happened! 

Thank you for this site, by the way.  I try not to miss a day. :)
