### ISSUE TITLE
People who get the right answer with their first guess not labelled as lucky

### ISSUE THREAD

**Issue by leahrickard** [hryanjones/guess-my-word#35]
Thank you for Guess My Word, I enjoy the daily challenge!

I've noticed that sometimes people aren't labelled as lucky when they got the word on their first guess. This seems like a bug to me.

![image](https://user-images.githubusercontent.com/19320290/85992953-b7f6b880-ba49-11ea-8b8a-eef8ffba14ae.png)

**Comment by hryanjones** [comment]
People are only currently labelled as lucky when they haven't played enough
to be on the long term board and their number of guesses is less than 5 (or
6, can't remember exact cutoff). There was someone who had a streak of
playing going for a long time and didn't like that he had been lucky once
and couldn't submit, which is why I started allowing submissions of 1 guess.

However, it looks like a fair number of people are abusing this, what about
this logic: if someone gets it in 1, for them it'll show that they're on
top of the board, but for everybody else it'll show that they're lucky?

**Comment by leahrickard** [comment]
I was wondering what the criteria were, thanks for that!

Your solution sounds reasonable. I guess otherwise, whatever you had the cutoff as, someone could work it out and abuse it.

**Comment by hryanjones** [comment]
Okay, finally for the time to add in the new logic. This type of abuse should show up a lot less, but feel free to reopen if you started seeing it again.
