### ISSUE TITLE
Hard Mode words not randomizing

### ISSUE THREAD

**Issue by jehovoid** [hryanjones/guess-my-word#53]
For many days in a row now, Hard Mode has been stuck in the "a"s and appears to just be going down the list in alphabetical order. Sadly this has not helped my score :P...

**Comment by hryanjones** [comment]
Oops!

I forgot to randomize the newly picked hard words so they were showing up in alphabetical order.

Sorry it took me so long to see this issue, I've been bad about checking email lately. (for future reference, I'm usually a bit more responsive with tweets to [@guessmyword1](https://twitter.com/guessmyword1) )

I'm pretty sure I've fixed this now, although because new words get released to folks in new timezones a little earlier, you may not see it fixed until the day after tomorrow.

Please do let me know if it doesn't get fixed and thanks so much for reporting the issue!
